---
title: "SeuratVisPro Tutorial"
author: "SeuratVisPro Team"
date: "2025-11-29"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{SeuratVisPro Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", fig.width = 7, fig.height = 5)
```

```{r}
library(SeuratVisPro)
library(Seurat)
library(ggplot2)
```

## Overview

SeuratVisPro adds innovative visualization and analysis helpers on top of Seurat v5.

## Example data

```{r}
obj <- SeuratVisProExample(n_cells = 300, n_genes = 800, n_clusters = 3, spatial = TRUE)
DimPlot(obj)
```

## QC panel

```{r}
VisQCPanel(obj, genes_ribo = "^RPL|^RPS")
```

## Cluster stability

```{r}
res <- VisClusterStability(obj, resolution_range = seq(0.2, 1.0, by = 0.2))
res$plot
```

## Marker atlas

```{r}
ma <- VisMarkerAtlas(obj, top_n = 5)
ma$plot
```

## Batch mixing

```{r}
obj$batch <- sample(c('A','B'), ncol(obj), replace = TRUE)
bm <- VisBatchAlign(obj, batch = 'batch')
bm$plot
```

## Gene trend

```{r}
VisGeneTrend(obj, features = c('G10','G20'), by = 'pseudotime')
```

## Ligand-receptor

```{r}
lr <- data.frame(ligand = paste0('G', 1:5), receptor = paste0('G', 6:10))
lrp <- VisLigRec(obj, lr_table = lr, group.by = 'seurat_clusters')
lrp$plot
```

## Cluster tree

```{r}
VisClusterTree(obj, dist.metric = 'correlation', linkage = 'average', show_heatmap = TRUE)
```

## Module score

```{r}
sets <- list(SetA = paste0('G', 1:10), SetB = paste0('G', 11:20))
VisMetaFeature(obj, feature_sets = sets, group.by = 'seurat_clusters')$plot
```

## Cell cycle

```{r}
s.genes <- paste0('G', 1:10); g2m.genes <- paste0('G', 11:20)
VisCellCycle(obj, s.genes, g2m.genes)$plot
```

## Shiny app

```{r eval=FALSE}
launchSeuratVisPro()
```
## Innovative visuals

```{r}
VisEmbeddingContour(obj, group.by = 'seurat_clusters')
VisRankedDotmap(obj, group.by = 'seurat_clusters', top_n = 6)
VisGeneCoexpHive(obj, genes = paste0('G', 1:12), threshold = 0.2)
```
